TG_SECRETS_VAR = "telegram_secret_token"
TG_SUBSCRIBERS_VAR = "telegram_subscribers"
TG_API_URL_BASE = "https://api.telegram.org/bot"
SNOWFLAKE_CONN_ID = "snowflake_default"
DEFAULT_DBT_PROJECT_DIR = "/opt/dbt_core"
DEFAULT_SNOWFLAKE_DB = "RETAIL_VAULT"
DEFAULT_SNOWFLAKE_WH = "COMPUTE_WH"
DEFAULT_SNOWFLAKE_ROLE = "ACCOUNTADMIN"