ALTER TABLE RETAIL_VAULT.RAW_VAULT.SAT_CUSTOMER_LF SET DATA_RETENTION_TIME_IN_DAYS = 7;

CREATE TABLE RETAIL_VAULT.RAW_VAULT.SAT_CUSTOMER_LF_BACKUP
CLONE RETAIL_VAULT.RAW_VAULT.SAT_CUSTOMER_LF
BEFORE (TIMESTAMP => DATEADD(minute, -5, CURRENT_TIMESTAMP()));

INSERT INTO RETAIL_VAULT.RAW_VAULT.SAT_CUSTOMER_LF
SELECT * FROM RETAIL_VAULT.RAW_VAULT.SAT_CUSTOMER_LF AT(OFFSET => -3600);
SELECT *
FROM RETAIL_VAULT.STAGING.STG_TPCH_CUSTOMER
BEFORE (TIMESTAMP => DATEADD(day, -1, CURRENT_TIMESTAMP()));
