version: 2

models:
  - name: stg_tpch_customer
    description: "Staging for TPCH CUSTOMER."
    columns:
      - name: hk_customer
        tests: [not_null, unique]
      - name: customer_key
        tests: [not_null, unique]
      - name: hashdiff
        tests: [not_null]
      - name: load_ts
        tests: [not_null]

  - name: stg_tpch_orders
    description: "Staging for TPCH ORDERS."
    columns:
      - name: hk_order
        tests: [not_null, unique]
      - name: hk_customer
        tests: [not_null]
      - name: hk_customer_order
        tests: [not_null, unique]
      - name: order_key
        tests: [not_null, unique]
      - name: hashdiff
        tests: [not_null]

  - name: stg_tpch_lineitem
    description: "Staging for TPCH LINEITEM."
    columns:
      - name: hk_order_lineitem
        tests: [not_null, unique]
      - name: hk_order
        tests: [not_null]
      - name: hk_part
        tests: [not_null]
      - name: hk_supplier
        tests: [not_null]
      - name: hashdiff
        tests: [not_null]

  - name: stg_tpch_part
    description: "Staging for TPCH PART."
    columns:
      - name: hk_part
        tests: [not_null, unique]
      - name: part_key
        tests: [not_null, unique]
      - name: hashdiff
        tests: [not_null]

  - name: stg_tpch_supplier
    description: "Staging for TPCH SUPPLIER."
    columns:
      - name: hk_supplier
        tests: [not_null, unique]
      - name: hk_nation
        tests: [not_null]
      - name: hk_supplier_nation
        tests: [not_null, unique]
      - name: supplier_key
        tests: [not_null, unique]
      - name: hashdiff
        tests: [not_null]

  - name: stg_tpch_partsupp
    description: "Staging for TPCH PARTSUPP."
    columns:
      - name: hk_part_supplier
        tests: [not_null, unique]
      - name: hk_part
        tests: [not_null]
      - name: hk_supplier
        tests: [not_null]
      - name: hashdiff
        tests: [not_null]

  - name: stg_tpch_nation
    description: "Staging for TPCH NATION."
    columns:
      - name: hk_nation
        tests: [not_null, unique]
      - name: hk_region
        tests: [not_null]
      - name: hk_nation_region
        tests: [not_null, unique]

  - name: stg_tpch_region
    description: "Staging for TPCH REGION."
    columns:
      - name: hk_region
        tests: [not_null, unique]

  - name: stg_customer_marketing
    description: "Staging for customer marketing seed."
    columns:
      - name: hk_customer
        tests: [not_null, unique]
      - name: customer_key
        tests: [not_null, unique]
      - name: hashdiff
        tests: [not_null]